name: Feature Request
description: Suggest a new feature or enhancement for DFBU
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please provide detailed information about your proposal.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Backup functionality
        - Restore functionality
        - Verification system
        - Profile management
        - User interface
        - Configuration management
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What workflow does it improve?
      placeholder: Describe the use case or pain point this feature would address
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed feature or enhancement
      placeholder: How should this feature work? What should the user experience be?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: What other approaches might solve this problem?

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: If you have technical insights, share implementation considerations
      placeholder: "e.g., Could use Python watchdog library for file monitoring, would require new dependency"

  - type: dropdown
    id: priority
    attributes:
      label: Priority Assessment
      description: How important is this feature to your workflow?
      options:
        - Critical (blocking my use of DFBU)
        - High (significant improvement to workflow)
        - Medium (nice to have)
        - Low (minor convenience)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information, mockups, examples, or references
      placeholder: Add any other context, screenshots, or examples here
